version: "3.2"
services:
  networth-api:
    build: ./networth-api
    environment: 
      FIXER_APIKEY: ${FIXER_APIKEY}
      DB_URI: ${DB_URI}
    ports:
      - 8080:8080
    networks:
      - api
      - db
    depends_on:
      - mongo
  networth-web:
    build: ./networth-web
    ports:
      - 8000:8000
    networks:
      - api
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - api
      - db
    # command: mongod --smallfiles --logpath=/dev/null # --quiet
volumes:
  mongo:

networks:
  api:
  db:
